<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}

<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [17]:
# One-Dimensional array
import numpy as np
d = np.arange(1,9)
print(d.dtype)





int64


In [18]:
# Two-Dimensional array

import numpy as np
d = np.zeros((2,3))
print(d.dtype)





float64


In [49]:
# Three-Dimensional array

import numpy as np

ar_3d = np.array([[[1 , 2 , 3]]])
print(ar_3d.dtype)






int64


### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [50]:
# Method one
import numpy as np

array = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
fliped = np.flip(array)
print(fliped)





[[[10  9  8  7]
  [ 7  6  5  4]
  [ 4  3  2  1]]]


In [39]:
# Method two
#>**hint**: use flipud function

import numpy as np

array = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
array2 = array.reshape((3,4))
fliped2 = np.flipud(array2)
print(fliped2)





[[ 7  8  9 10]
 [ 4  5  6  7]
 [ 1  2  3  4]]


## 6-Make this array as an array one dimensional

In [52]:
import numpy as np
array1 = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
edit = array1.flatten()
print(edit)

[ 1  2  3  4  4  5  6  7  7  8  9 10]


## 7- Create a 3X2 integer array and Prints its attributes¶
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

In [45]:
import numpy as np
array = np.zeros((3,2) , dtype = np.int16)
print(array.shape)
print(array.ndim)
print(array.itemsize)



(3, 2)
2
2


### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

In [55]:
import numpy as np
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
ordered = np.sort(sampleArray)
print(ordered)
request = ordered[0:5:2 , 1:4:2]
print(request)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


## 9-How is np.mean() different from np.average() in NumPy?

In [ ]:
np.average considers the weight of each point in the data while calculating the mean. It has the weight parameter, so it measures the mean with higher accuracy

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [57]:
import numpy as np
array = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
freq = np.unique(array)
print(freq)
count = np.bincount(array)
print(count)

[0 1 2 3 5]
[3 2 2 2 0 1]


## 11-Show how is arr[:,0] different from arr[:,[0]]

In [ ]:
first one gives a 2d array, while the last one gives 3d array

### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [46]:
import numpy as np
array1 = np.array([[15,16,17],[18,19,20],[21,22,23]])
array2 = np.array([[20,21,22],[23,24 ,25],[26,27,28]])
array1 * array2

array([[300, 336, 374],
       [414, 456, 500],
       [546, 594, 644]])

### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [62]:
import numpy as np

array1 = np.array([1,2,3] )
array2 = np.array([4,5,6] )
vstack = np.vstack((array1 , array2))
print(vstack)
hstack = np.hstack((array1 , array2))
print(hstack)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [ ]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


In [69]:
class Vehicle:
  def __init__(self, name,max_speed,mileage):
      self.name = name
      self.max_speed = max_speed
      self.mileage = mileage
  def seating_capacity(self, capacity):
    return f"The seating capacity of a {self.name} is {capacity} passengers"

class Bus(Vehicle):
  def __init__(self, name,max_speed,mileage):
    Vehicle.__init__(self, name, max_speed, mileage)

bus = Bus('bigBus', 60 , 1800)
print(bus.seating_capacity(50))

The seating capacity of a bigBus is 50 passengers


# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [85]:
# Problem_1 Link:


question = input('enter: ')
list = question.split("+")
array = np.array(list)
new_array = np.sort(array)
new = '+'.join(new_array)

print(new)

enter: 3+1+3+2+1+3
1+1+2+3+3+3


<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [70]:
# Problem_2 Link:
string = input("enter a word of length 1 to 100: ")
string = string.lower()
vowels = "aeuio"
for char in string:
    if char in vowels:
        string = string.replace(char , "")

dot = "."
string_new = ""
for char in string:
    string_new += dot + char
n = len(string)
if 1<=n<=100:
    print(string_new)

elif n <= 1 :
    print("try typing more than 1 letter")

elif n >= 100 :
    print("try typing less than 100 letters")



enter a word of length 1 to 100: ABcdfGH
.b.c.d.f.g.h
